# Japanese
lang_name: "日本語"
title: 高松コミュニティ教会
subtitle: 高松コミュニティ教会は、キリストの体である一つの教会として香川県内に4ヶ所。
btn_learn_more: 学ぶ も
btn_contact: Contact

# Language selector
lnselect_en:
lnselect_ja: selected="selected"

# Navigation menu text
navi_home: ホーム
navi_about_us: 私たちについて
navi_leadership: リーダーシップ
navi_events: イベント情報
navi_online_services: オンライン・サービス
navi_contact_us: お問い合わせ

# Locations
locations:
  mure:
    title: 牟礼インターナショナルチャペル
    image: "assets/img/mure-chapel.png"
    worship: 日曜日の礼拝は16:00から
    address: 〒761-0123 香川県高松市牟礼町原541
    phone: 0877777777
    mapurl: "https://maps.app.goo.gl/Jhxym5bmGCeJTgfq5"
  center:
    title: 高松クリスチャンセンター
    image: "assets/img/center-church.png"
    worship: 日曜日の礼拝は11:00から
    address: ２丁目-５-15 常磐町 高松市 香川県 760-0054
    phone: 0878342870
    maplink: "https://goo.gl/maps/ErcUk4JPFZZiXDvq7"
  setouchi:
    title: 瀬戸内チャペル
    image: "assets/img/seto-uchi-chapel.png"
    worship: 日曜日の礼拝は10:00から
    address: 〒760-0012 香川県高松市瀬戸内町２０−15
    phone: 0878359189
    maplink: "https://maps.app.goo.gl/v6siL37VoYorKzPg7"
  ayagawa:
    title: 高松コミュニティチャーチ綾川キリスト教会
    image: "assets/img/ayagawa.png"
    worship: 日曜日の礼拝は10:00から
    address: 〒761-2101 香川県綾歌郡綾川町畑田2110
    phone: 0878770433
    fbpage: "https://www.facebook.com/AyagawaChristChurch"
    maplink: "https://maps.app.goo.gl/GnxAoGavyQ9kjysC6"

# Leadership
leaders:
  takinami:
    name: Takinami
    display_name: Takinami Yoshii
    title: Pastor
    contact: https://tccsite.github.io/
    avatar: "assets/img/avatar.png"
    email: tcc-takinami@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  kenji:
    name: Kenji
    display_name: Takaoka Kenji
    title: Pastor
    contact: https://tccsite.github.io/
    avatar: "assets/img/avatar.png"
    email: tcc-kenji@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  mark:
    name: Mark
    display_name: Powell Mark
    title: Missionary
    contact: https://tccsite.github.io/
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  noriko:
    name: Noriko
    display_name: Mukai Noriko
    title: Elder
    contact: https://tccsite.github.io/
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  stella:
    name: Stella
    display_name: Cox Stella
    title: Missionary
    contact: https://tccsite.github.io/
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."

authors:
  takinami:
    name: Takinami
    display_name: Takinami Yoshii
    avatar: "assets/img/avatar.png"
    email: tcc-takinami@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  kenji:
    name: Kenji
    display_name: Takaoka Kenji
    avatar: "assets/img/avatar.png"
    email: tcc-kenji@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  mark:
    name: Mark
    display_name: Powell Mark
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  noriko:
    name: Noriko
    display_name: Mukai Noriko
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  stella:
    name: Stella
    display_name: Cox Stella
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
