# English
lang_name: "English"
title: Takamatsu Community Church
subtitle: Takamatsu Community Church is a body of Christ as one church on four campuses in Kagawa.
btn_learn_more: Learn more
# Language selector
lnselect_en: selected="selected"
lnselect_ja:

# Navigation menu text
navi_home: Home
navi_about_us: About us
navi_leadership: Leadership
navi_events: Events
navi_online_services: Online Services
navi_contact_us: Contact Us

# Locations
locations:
  mure:
    title: Mure International Chapel
    image: "assets/img/mure-chapel.png"
    worship: Sunday worship starts at 16:00
    address: 541 Murechohara, Takamatsu, Kagawa 761-0123
    phone: 0877777777
    mapurl: "https://maps.app.goo.gl/Jhxym5bmGCeJTgfq5"
  center:
    title: Christian Center
    image: "assets/img/center-church.png"
    worship: Sunday worship starts at 11:00
    address: 2-chome-5-15 Tokiwacho, Takamatsu, Kagawa 760-0054,
    phone: 0878342870
    mapurl: "https://goo.gl/maps/ErcUk4JPFZZiXDvq7"
  setouchi:
    title: Setouchi Chapel
    image: "assets/img/seto-uchi-chapel.png"
    worship: Sunday worship starts at 10:00
    address: 20-15 Setouchicho, Takamatsu, Kagawa 760-0012
    phone: 0878359189
    mapurl: "https://maps.app.goo.gl/v6siL37VoYorKzPg7"
  ayagawa:
    title: Ayagawa Christ Church
    image: "assets/img/ayagawa.png"
    worship: Sunday worship starts at 10:00
    address: 2110 Hatada, Ayagawa, Ayauta District, Kagawa 761-2101
    phone: 0878770433
    fbpage: "https://www.facebook.com/AyagawaChristChurch"
    mapurl: "https://maps.app.goo.gl/GnxAoGavyQ9kjysC6"

# Leadership
authors:
  takinami:
    name: Takinami
    display_name: Takinami Yoshii
    avatar: "assets/img/avatar.png"
    email: tcc-takinami@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  kenji:
    name: Kenji
    display_name: Takaoka Kenji
    avatar: "assets/img/avatar.png"
    email: tcc-kenji@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  mark:
    name: Mark
    display_name: Powell Mark
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  noriko:
    name: Noriko
    display_name: Mukai Noriko
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
  stella:
    name: Stella
    display_name: Cox Stella
    avatar: "assets/img/avatar.png"
    email: tcc-mpowell@gmail.com
    web: https://www.tc.church
    twitter: https://twitter.com/tcc
    description: "Write a short description of the leader here. You are currently previewing TCC site demo."
