# English
lang_name: "English"
title: Takamatsu Community Church

# Locations
locations:
  mure:
    title: Mure International Chapel
    image: 'assets/img/mure-chapel.png'
    worship: Sunday worship starts at 16:00
    address: 541 Murechohara, Takamatsu, Kagawa 761-0123
    phone: 0877777777
    mapurl: 'https://maps.app.goo.gl/Jhxym5bmGCeJTgfq5'
  center:
    title: Christian Center
    image: 'assets/img/center-church.png'
    worship: Sunday worship starts at 11:00
    address: 2-chome-5-15 Tokiwacho, Takamatsu, Kagawa 760-0054,
    phone: 0878342870
    mapurl: 'https://goo.gl/maps/ErcUk4JPFZZiXDvq7'
  setouchi:
    title: Setouchi Chapel
    image: 'assets/img/seto-uchi-chapel.png'
    worship: Sunday worship starts at 10:00
    address: 20-15 Setouchicho, Takamatsu, Kagawa 760-0012
    phone: 0878359189
    mapurl: 'https://maps.app.goo.gl/v6siL37VoYorKzPg7'
  ayagawa:
    title: Ayagawa Christ Church
    image: 'assets/img/ayagawa.png'
    worship: Sunday worship starts at 10:00
    address: 2110 Hatada, Ayagawa, Ayauta District, Kagawa 761-2101
    phone: 0878770433
    #fbpage: 'https://www.facebook.com/AyagawaChristChurch'
    mapurl: 'https://maps.app.goo.gl/GnxAoGavyQ9kjysC6'
